package com.moto.mvp.opiniongeneration.core.constant;

public enum CacheKey
{
    DEPRECIATION_RULE_CACHE,
    EXACT_MATCH_DEPRECIATION_RULE_CACHE,
    ODOMETER_DEPRECIATION_RULE_CACHE,
    VEHICLE_EXTRA_FIXED_COST_CACHE,
    VEHICLE_TYRE_FIXED_COST_CACHE,
    VEHICLE_BATTERY_FIXED_COST_CACHE,
    VEHICLE_HORN_FIXED_COST_CACHE,
    VEHICLE_OTHER_LIGHTS_FIXED_COST_CACHE,
    VEHICLE_PAINT_FINISH_FIXED_COST_CACHE,
    VEHICLE_BODY_COLOUR_FIXED_COST_CACHE,
    VEHICLE_PART_PERCENTAGE_RULE_CACHE,
    FLAGGING_RULE_CACHE,
    MARKET_ADJUSTMENT_RULE_CACHE,
    VEHICLE_PART_MAX_RATING_CACHE,
    INSURANCE_COVER_RULE_CACHE
    ;
    public String getCacheKey()
{
    return this.toString();
}
}
