package com.moto.mvp.opiniongeneration.core.constant;

public enum EndpointKey
{
    OPINION_GENERATION_ENDPOINT,
    DEPRECIATION_RULE_ENDPOINT,
    EXACT_MATCH_DEPRECIATION_RULE_ENDPOINT,
    ODOMETER_DEPRECIATION_RULE_ENDPOINT,
    VEHICLE_EXTRA_COST_ENDPOINT,
    VEHICLE_TYRE_COST_ENDPOINT,
    VEHICLE_BATTERY_COST_ENDPOINT,
    VEHICLE_HORN_COST_ENDPOINT,
    VEHICLE_OTHER_LIGHTS_COST_ENDPOINT,
    VEHICLE_PAINT_FINISH_COST_ENDPOINT,
    VEHICLE_BODY_COLOUR_COST_ENDPOINT,
    VEHICLE_PART_PERCENTAGE_RULE_ENDPOINT,
    FLAGGING_RULE_ENDPOINT,
    MARKET_ADJUSTMENT_RULE_ENDPOINT,
    VEHICLE_MAKE_ENDPOINT,
    VEHICLE_MODEL_ENDPOINT,
    COUNTRY_ENDPOINT,
    ENGINE_TYPE_ENDPOINT,
    BODY_COLOUR_ENDPOINT,
    VEHICLE_EXTRA_ENDPOINT,
    VEHICLE_STATUS_ENDPOINT,
    INSURANCE_COVER_RULE_ENDPOINT,
    VEHICLE_CONDITION_ENDPOINT,
    VEHICLE_CONDITION_TYPE_ENDPOINT,
    VEHICLE_CONDITION_RATING_ENDPOINT
    ;

    public String getEndPointKey()
    {
        return this.toString();
    }
}
