package com.moto.mvp.opiniongeneration.core.constant;

public enum RuleKey
{
    DEPRECIATION_RULE,
    EXACT_MATCH_DEPRECIATION_RULE,
    ODOMETER_DEPRECIATION_RULE,
    VEHICLE_EXTRA_FIXED_COST_RULE,
    VEHICLE_TYRE_FIXED_COST_RULE,
    VEHICLE_BATTERY_FIXED_COST_RULE,
    VEHICLE_HORN_FIXED_COST_RULE,
    VEHICLE_OTHER_LIGHTS_FIXED_COST_RULE,
    VEHICLE_PAINT_FINISH_FIXED_COST_RULE,
    VEHICLE_BODY_COLOUR_FIXED_COST_RULE,
    VEHICLE_CONDITION_RULE,
    FLAGGING_RULE,
    MARKET_ADJUSTMENT_RULE,
    INSURANCE_COVER_RULE
    ;
    public String getRuleKey()
    {
        return this.toString();
    }
}