package com.moto.mvp.opiniongeneration.core.constant;

public enum ServiceKey
{
    OPINION_GENERATION_SERVICE,
    DEPRECIATION_RULE_SERVICE,
    EXACT_MATCH_DEPRECIATION_RULE_SERVICE,
    ODOMETER_DEPRECIATION_RULE_SERVICE,
    VEHICLE_EXTRA_COST_SERVICE,
    VEHICLE_TYRE_COST_SERVICE,
    VEHICLE_BATTERY_COST_SERVICE,
    VEHICLE_HORN_COST_SERVICE,
    VEHICLE_OTHER_LIGHTS_COST_SERVICE,
    VEHICLE_PAINT_FINISH_COST_SERVICE,
    VEHICLE_BODY_COLOUR_COST_SERVICE,
    VEHICLE_PART_PERCENTAGE_RULE_SERVICE,
    FLAGGING_RULE_SERVICE,
    MARKET_ADJUSTMENT_RULE_SERVICE,
    VEHICLE_MAKE_SERVICE,
    VEHICLE_MODEL_SERVICE,
    COUNTRY_SERVICE,
    ENGINE_TYPE_SERVICE,
    BODY_COLOUR_SERVICE,
    VEHICLE_EXTRA_SERVICE,
    VEHICLE_STATUS_SERVICE,
    INSURANCE_COVER_RULE_SERVICE,
    VEHICLE_CONDITION_SERVICE,
    VEHICLE_CONDITION_TYPE_SERVICE,
    VEHICLE_CONDITION_RATING_SERVICE
    ;

    public String getServiceKey()
    {
        return this.toString();
    }
}
